### ISSUE TITLE
Attribute returns % in the number (battery_level: 87%)

### ISSUE THREAD

**Issue by chadlyy** [maxwroc/battery-state-card#103]
**Describe what is wrong**
I have a motion sensor that has an attribute with the battery level as "87%". I believe the card is looking for numeric values only and isn't understanding the % that is included.  Any suggestions on how to utilize the card in this scenario?

**YAML configuration**
HACS

# paste your card configuration here
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
entities:
  - entity: binary_sensor.master_bath_motion
  - entity: sensor.front_door_battery_level
title: Color gradient
type: 'custom:battery-state-card'

**Screenshot**
<img width="394" alt="Screen Shot 2020-07-17 at 6 15 52 PM" src="https://user-images.githubusercontent.com/54695185/87841361-95420d80-c859-11ea-8fec-1a386a6bfd02.png">

**Version**
1.4.0

**Comment by maxwroc** [comment]
I think that such states are not supported currently. I will double check next week. One thing what you can try meanwhile is to use 'multiplier' property and set it to 1. Give it a try and let me know.

If that is not feasible I'll add support in the next release

**Comment by chadlyy** [comment]
Thanks for the quick response!  No luck with the multiplier.  I was thinking maybe a sensor template, but not sure how to code that to strip out the % from that value.  I'll play around with that.  Thank you and great work on this code! :)

**Comment by maxwroc** [comment]
Sorry that it took so long, it will be available in v1.5.0 release

**Comment by maxwroc** [comment]
Reopening for time being - will close it once it is released
