### ISSUE TITLE
Include attribute "battery_critical"

### ISSUE THREAD

**Issue by Larx** [maxwroc/battery-state-card#107]
I have a Nuki lock which exposes battery state as attribute "battery_critical: false/true". Could the card be updated to handle this scenario? Thanks.

**Comment by maxwroc** [comment]
Look at the `state_map` property
https://github.com/maxwroc/battery-state-card#common-options

It is supported already:
https://maxwroc.github.io/lovelace-card-tester/?key=5f240b25dc263a7b80b10765 (this page doesn't work on iOS devices)
![image](https://user-images.githubusercontent.com/8268674/89033896-bf063480-d32f-11ea-86eb-3cf83073fc4c.png)
