### ISSUE TITLE
May I suggest a different default color schema and behaviour?

### ISSUE THREAD

**Issue by SeLLeRoNe** [maxwroc/battery-state-card#15]
Hi there,

I know colors and thresholds can be customized, but I would still like to suggest to have the default color schema to be more "brillant"

For intance, this is what I did create on my own:
![image](https://user-images.githubusercontent.com/9599441/80414015-a883b380-88d0-11ea-8693-43b215449ab3.png)

This is the card:
![image](https://user-images.githubusercontent.com/9599441/80414040-b0dbee80-88d0-11ea-9ea3-91e409699a02.png)

If interested, those are the color thresholds I used:
```
                    --paper-item-icon-color:
                      {% if is_state(config.entity, 'unknown') %}
                        rgb(128, 128, 128);
                      {% elif states(config.entity)|int > 100 %}
                        rgb(128, 128, 128);
                      {% elif states(config.entity)|int >= 80 %}
                        rgb(0, 153, 51);
                      {% elif states(config.entity)|int >= 60 %}
                        rgb(0, 153, 0);
                      {% elif states(config.entity)|int >= 40 %}
                        rgb(255, 128, 0);
                      {% elif states(config.entity)|int >= 20 %}
                        rgb(204, 102, 0);
                      {% elif states(config.entity)|int >= 0 %}
                        rgb(153, 0, 0);
                      {% else %}
                        rgb(128, 128, 128);
                      {% endif %}
                  }```

Also, Where is the icon coming from? I thought it was from the sensor itself but it doesn't look like (see the Motorola phone differences), it should so that the "charging" state is kept.

Also, not sure it's easy to do or not, but maybe have an option to define "charging_entity" where you can define the binary_sensor that defines if the battery is charging on not in order to have the right icon would be nice, maybe with a second line saying "Charging" as per my current setup.

Of course, those are just suggestions :)

Thanks
Andrea

**Comment by maxwroc** [comment]
Hey, first of all thank you for all the suggestions. Answers below:

* Changing default colors
  I was thinking about changing the default colors but decided to not do it because the default ones are taken from your theme. This means they should be universal and adjusting to the entire Lovelace theme. I know that in some cases they don't look very nice but I can blame now your theme ;). Anyway I will consider this and maybe change in nearest future. 
* Entity icon
  AFAIK there is no way to get the default icon in the custom card (I might be wrong). The entity icon which you see on standard cards is based on entity device_class attribute and it's state. Can you tell me what is the device class of your entity? I have checked the HA source code looking for charging icon but I don't see it there so I wonder how is it set in your case. Do you have some integration installed for it?
* Charging indicator
  Yes I'm planning to add special icon (same as in your example) in the nearest future. You would be able to use this or separate entity state to set it. So something like:
  ```yaml
  - type: "custom:battery-state-card"
    entities: 
      - entity: sensor.android_battery_level
        charging:
          - entity: binary_sensor.android_charging
  ```
  or

  ```yaml
  - type: "custom:battery-state-card"
    entities: 
      - entity: sensor.android_battery_level
        charging:
          - state: 4
  ```
  In the first case separate sensor will be used as charging indication while in the second one the current state of the `sensor.android_battery_level` entity. I've heard that there are sensors which have a special state value indicating charging state.
  I hope that this would solve your issue

**Comment by SeLLeRoNe** [comment]
Hi, 

thanks for your response, I do use device_class battery but I do use icon_template to override the icon (https://github.com/SeLLeRoNe/HA-Config/blob/master/entities/sensors/andrea_motorola_battery.yaml):
```
    icon_template: >
      {% if state_attr('device_tracker.andrea_xt1032', 'battery_level') %}
        {% set battery_level = state_attr('device_tracker.andrea_xt1032', 'battery_level') | int %}
      {% elif not is_state('input_text.andrea_xt1032_battery', 'unknown') %}
        {% set battery_level = states('input_text.andrea_xt1032_battery') | int %}
      {% else %}
        mdi:battery-unknown
      {% endif %}
      {% if battery_level is defined %}
        {% if battery_level == 100 %}
          {% if is_state('binary_sensor.andrea_xt1032_charging', 'on') %}
            mdi:battery-charging-100
          {% elif is_state('input_boolean.andrea_xt1032_charging', 'on') %}
            mdi:battery-charging-100
          {% else %}
            mdi:battery
          {% endif %}
        {% elif battery_level >= 10 %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if is_state('binary_sensor.andrea_xt1032_charging', 'on') %}
            mdi:battery-charging-{{ battery_round }}
          {% elif is_state('input_boolean.andrea_xt1032_charging', 'on') %}
            mdi:battery-charging-{{ battery_round }}
          {% else %}
            mdi:battery-{{ battery_round }}
          {% endif %}
        {% elif battery_level >= 5 %}
          {% if is_state('binary_sensor.andrea_xt1032_charging', 'on') %}
            mdi:battery-charging-outline
          {% elif is_state('input_boolean.andrea_xt1032_charging', 'on') %}
            mdi:battery-charging-outline
          {% else %}
            mdi:battery-outline
          {% endif %}
        {% elif battery_level >= 0 %}
          {% if is_state('binary_sensor.andrea_xt1032_charging', 'on') %}
            mdi:battery-charging-outline
          {% elif is_state('input_boolean.andrea_xt1032_charging', 'on') %}
            mdi:battery-charging-outline
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% else %}
          mdi:battery-unknown
        {% endif %}
      {% endif %}
```

Once you implement the "charging entity", will you also be able to add the second line that sais "Charging" too? (maybe that might be configurable because others might not want to see that text)

**Comment by SeLLeRoNe** [comment]
For the charging-line maybe the option should be something like this (following your previous example):
```
- type: "custom:battery-state-card"
  entities: 
    - entity: sensor.android_battery_level
      charging:
        entity: binary_sensor.android_charging
        show_charging_state: true
```

**Comment by SeLLeRoNe** [comment]
Also now that I review it, in the charging group to mantain the HA standard maybe it's worth to use entity_id instead of entity :)

**Comment by maxwroc** [comment]
Just added support for charging state. It will be available in v1.1.0

I'll open separate item for secornary_info support as I want to make it more generic - not only for indicating charging

**Comment by SeLLeRoNe** [comment]
Cheers :)

**Comment by SeLLeRoNe** [comment]
Quick one, I have added the custom_threshold to match my current config, is it possible to also use it for "unknown" devices? 
I tried but doesn't look like :)


Thanks

**Comment by SeLLeRoNe** [comment]
@maxwroc would you like me to open a different issue for my last response on this issue?

Let me know,
Thanks

**Comment by maxwroc** [comment]
The unknown is always shown as a default icon color. If you want to have the override for this please create a separate issue. I'll think about it
