### ISSUE TITLE
Add posibilty to change battery icon

### ISSUE THREAD

**Issue by azrael783** [maxwroc/battery-state-card#158]
**Is your feature request related to a problem? Please describe.**
I am using the card to display the status of my printer cartridges and it would be nice to change the battery icon to another one.

**Describe the solution you'd like**
The benct/lovelace-battery-entity-row already allows you to change the icon. See [here](https://github.com/benct/lovelace-battery-entity-row)

**Additional context**

**Comment by maxwroc** [comment]
Ok I will add a way to override the default icon
