### ISSUE TITLE
Ability to set thresholds on a per entity basis

### ISSUE THREAD

**Issue by danielbrunt57** [maxwroc/battery-state-card#167]
**Is your feature request related to a problem? Please describe.**
No Problem

**Describe the solution you'd like**
Be able to use color_gradient and/or color_thresholds within individual entities

**Comment by maxwroc** [comment]
It should be possible now. If it doesn't work then we have a bug. Please double check and if it really doesn't work please paste your config

**Comment by danielbrunt57** [comment]
Great!  Seems to work fine.  Thanks!

![New battery-state-card](https://user-images.githubusercontent.com/49846893/98971409-f60aeb00-24c5-11eb-8f92-19208d12de2c.PNG)
