### ISSUE TITLE
Ability to overwrite "unit_of_measurement"

### ISSUE THREAD

**Issue by KKnishev** [maxwroc/battery-state-card#180]
It will be great to overwrite the entities measurement with any others.
unit_of_measurement: "lqi"
At this way mod will work not for batteries only with "%", but with any other entities, like this:
![link](https://user-images.githubusercontent.com/22073966/100787495-cac04f80-3424-11eb-9165-3677194cb12d.png)

**Comment by maxwroc** [comment]
Good idea and very easy to implement

**Comment by Philou93260** [comment]
A new possibility with flower monitoring example with moisture

**Comment by KKnishev** [comment]
sorry for noob's question, could you please annonces a plans with this update?

**Comment by maxwroc** [comment]
Currently I'm rewriting the card code. I don't have too much spare time so the progress is not as fast as I'd like it to be. 

I don't want to work on any new features before refactoring work is done (bugfixes are not being on hold and should be released ASAP). If you (or anyone else) would like to do it and send PR I'm perfectly fine with it (I just don't want to focus myself on anything else ATM)

Please try to be patient and the v2 release should bring buch of new features including this one.
