### ISSUE TITLE
Please add feature, to round the decimals

### ISSUE THREAD

**Issue by cokeman0** [maxwroc/battery-state-card#184]
![2c4008238dda70184d8384c5ddc8e3f138b7e6e6](https://user-images.githubusercontent.com/6389802/101839914-81b67c80-3b43-11eb-9ee6-57bca7c82841.jpeg)

Possibility to round to 0 decimals

**Comment by cclarke99** [comment]
+1 for this as my batteries are all over the place

**Comment by archipita** [comment]
+1
I am using attributes and multipliers, therefore a round function would be really appreciated! :)

![image](https://user-images.githubusercontent.com/10539311/112729992-46dc2700-8f2f-11eb-97ef-106d6ebbd67a.png)

**Comment by p4mr** [comment]
+1 for this - Ability to round and set number of decimal places would be really useful

**Comment by gotsila** [comment]
Hello, can you please show me the code? i am also struggling with mutlipliers. i have 3 Homematic Thermostat, they only provide Batterie Voltage e. g. 3v(good) - 2.3v (bad)
