### ISSUE TITLE
Make card title optional

### ISSUE THREAD

**Issue by hmmbob** [maxwroc/battery-state-card#19]
Hi!

Great card! One improvement I'd like to suggest is to have the ability to not show the (default) header/card title (Battery Levels). 

For example, the default Lovelace entities card will not set a header unless specifically defined in the config. This is useful if you use something else to create headers (I'm using markdown cards for instance).

**Comment by maxwroc** [comment]
Good point. I'll make it optional

**Comment by maxwroc** [comment]
Will be optional in v1.1.0

**Comment by hmmbob** [comment]
Wow you're quick! Thanks!
