### ISSUE TITLE
Custom element doesn't exist: battery-state-card

### ISSUE THREAD

**Issue by bran2000** [maxwroc/battery-state-card#191]
Hello, i try to add the card to install the basic 
type: custom:battery-state-card
title: "Battery levels"
entities:
  - sensor.bathroom_motion_battery_level
  - sensor.bedroom_balcony_battery_level
  - entity: sensor.bedroom_motion_battery_level
    name: "Bedroom motion sensor"

```
this is the error it can't find the card 

Custom element doesn't exist: battery-state-card.
type: 'custom:battery-state-card'
title: Battery levels
entities:
  - sensor.test
  - sensor.tets
  - entity: sensor.test
    name: Bedroom motion sensor


i installed from HACS so i don't understand why it's not working

**Version**
version 2020.12.1

Thanks for the help

**Comment by maxwroc** [comment]
Depends what kind of lovelace configuration you have. If you have [yaml mode](https://www.home-assistant.io/lovelace/dashboards-and-views/) on you need to add the entry in ui-lovelace.yaml.

After adding such entry you need to restart home assistant (not sure if it is required for the regular/ui-configuration mode).
