### ISSUE TITLE
Support for Tado's battery sensors

### ISSUE THREAD

**Issue by timbru31** [maxwroc/battery-state-card#197]
**Is your feature request related to a problem? Please describe.**
Since the upgrade of HA to 2021.1 the Tado (smart heating solution) sensors have been reworked:
> The Tado Bridge sensor has been removed and replaced by its corresponding device sensor.

This results in new binary sensors which report the battery state:  
The corresponding sensors toggle between `binary_sensor.vaXXXXX_battery_state` `on`  and `off`

However, the state card just shows question marks for these entities.

**Describe the solution you'd like**

It would be great if the state card could display those entities correctly, either with green (full, state off) or red (empty, needs replacement, state on)

**Additional context**
![Screenshot_2021-01-10 Overview - Home Assistant](https://user-images.githubusercontent.com/838003/104123154-5640d080-5341-11eb-95fc-1c978b16b63c.png)
![2](https://user-images.githubusercontent.com/838003/104123155-56d96700-5341-11eb-8d0f-b0e3b253e89f.png)
![1](https://user-images.githubusercontent.com/838003/104123157-5771fd80-5341-11eb-9ac6-ace46587d44a.png)
![Screenshot_2021-01-10 Developer Tools - Home Assistant](https://user-images.githubusercontent.com/838003/104123158-5771fd80-5341-11eb-83c8-b2800054efae.png)

**Comment by maxwroc** [comment]
It should be possible to achieve currently. Look at `state_map` option. Note that this option can be configured per individual entity or for all of them (via [card-level settings](https://github.com/maxwroc/battery-state-card#common-options))
https://github.com/maxwroc/battery-state-card#non-numeric-state-values

**Comment by timbru31** [comment]
Oh neat, sorry I was not aware of this option. I'll test this later and close the issue if it works fine 👍
