### ISSUE TITLE
using with co2 level

### ISSUE THREAD

**Issue by Philou93260** [maxwroc/battery-state-card#212]
**Is your feature request related to a problem? Please describe.**
I find this card wonderful and I would like to adapt it with the level of co2

**Describe the solution you'd like**
the same thing with the color codes according to the level of co2

**Additional context**
I am new, I am willing to help as much as I can.

**Comment by maxwroc** [comment]
This is yet another idea (look at #180) of adapting this card for other entity types. I like it!

**Comment by Elnio13** [comment]
I want to use this map to display LQI
