### ISSUE TITLE
[iOS] icon, name & state not on the same row

### ISSUE THREAD

**Issue by migo-dev** [maxwroc/battery-state-card#215]
First of all, thanks for this great card!

**Describe the bug**

In the iOS App (iPhone 12 mini) the card doesn't look how it's supposed to. The icon, name and state take up a row each, which makes the card unusable unfortunately.

**How to reproduce**

--

**Expected behavior**

It should look like a normal entities card. No problems on my PC btw.

**YAML configuration**
```
collapse: 10
color_gradient:
  - '#aeaeae'
  - '#8f8f8f'
  - '#444444'
entities:
...
sort_by_level: asc
type: 'custom:battery-state-card'
```

**Screenshots**

![IMG_0149](https://user-images.githubusercontent.com/57773976/107449713-58ff3300-6b44-11eb-817e-a1ebe6953dda.PNG)

**Version**
 v1.6.3

**Comment by sunde41** [comment]
+1

**Comment by maxwroc** [comment]
Sorry to hear that. Just wanted to let you know that unfortunatelly I won't be able to fix it quickly - I cannot reproduce it. I don't have a macbook nor iPhone. On my iPad the card looks fine.

Was it like that since ever or is it happening after some update?

**Comment by migo-dev** [comment]
That's okay - I will try to investigate the problem. I'm a total noob, but it might be a fun project :-)

Hard to tell honestly. I'm only using an iPhone since November - and I think - it's been that way ever since.

**Comment by migo-dev** [comment]
I just checked on my iPad and the card shows the same way as on my iPhone - very strange it's not happening to you.

**Comment by migo-dev** [comment]
Just for the record, I tried to look into this - but failed hard 😆 way too complicated for my beginner skills..

**Comment by maxwroc** [comment]
I assume it happens even with the simplest configuration (few entities on the list and no other settings), right?

**Comment by migo-dev** [comment]
Great hint thanks, I tried with basic settings and it worked fine - I have to admit, the source of this was the following card-mod I had applied:
```
style: |
  ha-card {
    font-family: Roboto Condensed,sans-serif;
  }
```
