### ISSUE TITLE
tap_action

### ISSUE THREAD

**Issue by domoson** [maxwroc/battery-state-card#22]
Hi, this card is really nice!

Would it be difficult to add `tap_action` (and `hold_action`)? I would like to open the more-info view when tapping on an entity to show the history.

Thanks!

**Comment by maxwroc** [comment]
Hi, 

It's a dupe of #8 

It is done already and awaiting release (v1.1.0 will have it). There is only tap_action support though - I hope that will be sufficient. Adding hold_action shouldn't be a big deal but I wonder if it can be actually very useful. Let me know.

You can read more about it in v1.1.0 readme [here](https://github.com/maxwroc/battery-state-card/tree/vNext#tap-action)

**Comment by domoson** [comment]
Oh I did not see that, sorry for that! Yes this is great, thank you.

Regarding hold_action: up to you. I can see use cases (e.g. tap for history, hold to navigate to a saparate lovelace page or other actions), but not high priority. If it is trivial to add, I would suggest to add it, otherwise not.

Thanks again!
