### ISSUE TITLE
Support secondary info

### ISSUE THREAD

**Issue by maxwroc** [maxwroc/battery-state-card#25]
It might be useful to see when entity changed it's status last time or print any other attribute

As per ask from #15 it may as well indicate charging in progress state

**Comment by pmazz** [comment]
Hi, 👍 for the idea.

I've just started using your card and this is something I'd like to achive:
![image](https://user-images.githubusercontent.com/44721151/80908379-bba6e100-8d1f-11ea-9b2b-2f5e1343823b.png)
The ideal format would be: -prefix- -value- -suffix-.

Thanks!

**Comment by maxwroc** [comment]
I'm adding similar option as it is in native cards/entities. You can specify attribute which you want to display there
