### ISSUE TITLE
Show entity / device area

### ISSUE THREAD

**Issue by toshymaeda** [maxwroc/battery-state-card#253]
**Is your feature request related to a problem? Please describe.**
Possibility to show the entity area which my device is in.

**Additional context**
Since now its possible to add area to entities / devices, it would be nice if this information was visible on the card, adding some sort of "location" feature.

**Comment by maxwroc** [comment]
Unfortunatelly I cannot find any info/docs about the area information available from card perspective. HA state object doesn't seem to have that info
