### ISSUE TITLE
Update attribute battery level

### ISSUE THREAD

**Issue by nico78700** [maxwroc/battery-state-card#257]
Hello,

Great work. i'm looking for update battery level status for my tablet.

I used the service homeassistant.update_entity on the entity id

But no update of my entity attribute.

If i used homeassistant.reload. I see the reload but the update is KO.
Thanks to help me

Nicolas

**Comment by maxwroc** [comment]
Sorry but I don't understand what are your trying to do exacly and how is this issue related to the battery-state-card.

It depends how you are trying to update the entity. Attributes should be provided together with the status during the update.

**Comment by nico78700** [comment]
Thank you fr your reply.
I found my error. HA was not started on my tablet
