### ISSUE TITLE
HA 2021.6 Lit version upgrade

### ISSUE THREAD

**Issue by hmmbob** [maxwroc/battery-state-card#265]
**Describe the bug**

Raising for awareness:

This card is importing Lit in a way that might break in HA 2021.6 which ships with Lit 2.0

For more information, see https://developers.home-assistant.io/blog/2021/05/19/lit-2.0/

**Comment by maxwroc** [comment]
Thanks for the heads-up!

**Comment by maxwroc** [comment]
@hmmbob So far it looks like it works although there is a notification in the dev console. I guess HA devs added a workaround to still support cards which were not migrated. 

I haven't merged the PR yet because it increases card size significantly (x3).
