### ISSUE TITLE
not working in glance card entities?

### ISSUE THREAD

**Issue by DiggiD** [maxwroc/battery-state-card#27]
trying to implement in a glance card doest seem to work. 

`card:`
`  entities:`
`    type: 'custom:battery-state-card'`
`    color_gradient:`
`        '#ff0000'`
`        '#ffff00'`
`        '#00ff00'`
`    entities:`
`        entity: sensor.iphone_battery_state`
`show_name: false`
`type: glance`

edit: can't seem to post this with the indentation for some reason

**Comment by maxwroc** [comment]
Glance card doesn't allow nested cards, you can just use entities. Please read glance card documentation: https://www.home-assistant.io/lovelace/glance/
