### ISSUE TITLE
Notifications on low battery level

### ISSUE THREAD

**Issue by AseKarlsson** [maxwroc/battery-state-card#285]
Hi,

Great Card!
Have you considered the possibility to send notifications on low battery levels, just notification in HA Notifications would be sufficient? 

//Ase

**Comment by maxwroc** [comment]
In general cards are not suposed to do such things. You need to remnember that their code is exactuted only when they are loaded on the page. Such notifications should be done via automation

**Comment by AseKarlsson** [comment]
Thanks for the fast reply, I will start to look for some automation to do the job.

//Ase
