### ISSUE TITLE
add last-changed

### ISSUE THREAD

**Issue by hugosbnarciso** [maxwroc/battery-state-card#308]
Possible to add a last-changed tag so we can see when the sensor was last-changed on the card itself? Just like entity cards work.

Thanks,
Great work!

H

**Comment by maxwroc** [comment]
It is possible already. Please read documentation about secondary_info. Here is the example with last-updated 
https://github.com/maxwroc/battery-state-card#secondary-info

**Comment by hugosbnarciso** [comment]
Ups my bad,

thanks
H
