### ISSUE TITLE
As new battery powered devices comes and goes, and names change all the time

### ISSUE THREAD

**Issue by oywino** [maxwroc/battery-state-card#353]
**Is your feature request related to a problem? Please describe.**
With tens, if not hundreds of battery powered devices, it becomes unmanageable to maintain a correct list of all the entity names

**Describe the solution you'd like**
I like your card approach, but will it be able to automatically add new entities and remove deleted once?

**Additional context**
I once found a Node-Red Java-Script that does exactly that, but the output is in the form of an html file and not a Lovelace card. But the solution suggests that it should be doable to have auto-maintenance of the entity-list. Regretfully, I can no longer remember who made the original script, but it work well. I'm having it update the report at 8PM every day.  Entities are selected based on attribute.device_class=battery which so far seems to catch-all. Then the java-script that produce the report, looks like this:

```
var Page="<!DOCTYPE html><html lang=\"en-US\"><head><meta name=\"Battery status of all devices\" content=\"Battery Check\"><meta http-equiv=\"cache-control\" content=\"no-cache\"></head><body <body bgcolor=\"black\" text=\"white\"> \n";
var d = new Date();
Page = Page + "<h3><center>Battery Check - " + d + "</center></h3>";

var ThisArray = msg.payload;
ThisArray.forEach(myFunction);

function myFunction(item, index) 
{
  var BatLevel10 = Math.round(item.state/10);
  
  // Pick a font color for State (battery %) and bar graph
  if (BatLevel10 > 7) { CFont =  "<font color=\"#00FF00\">";  }         // Green  8-10
    else if (BatLevel10 > 5) { CFont =  "<font color=\"#FFFF00\">";  }  // Yellow 6-7
      else { CFont = "<font color=\"#FF0000\">";  }                     // Red    0-4
  
  // State and Title for each item    
  Page = Page + CFont + "<b>" + item.state + " %</font></b>&nbsp&nbsp&nbsp";
  Page = Page + "<font color =\"#FFFFFF\">" + item.attributes.friendly_name + "</font></b>";
  Page = Page + "<BR> \n ";
  
  // Ultra Simple Bar Graph in Green, Yellow, Red
  Page = Page + CFont;
  for (var i = 0; i < BatLevel10; i++) { Page = Page +  "\&#9608\&#9608"; }  // Solid Square
  for (var j = BatLevel10; j < 10; j++) { Page = Page + "\&#9617\&#9617"; }  // Shaded Square Light

  // Extra info in dark gray
  Page = Page + "</font><BR><font color =\"#25383C\"><b>Entity_id:</b> " + item.entity_id + "</font></BR> \n ";  //Gray
  Page = Page + "<BR> \n"
}

msg.payload = Page + "</body></html>";
return msg;
```
Here's a sample clip of the output file:
![image](https://user-images.githubusercontent.com/18447119/146998463-e945cdaf-861a-4770-97e7-600d4ba18117.png)

Perhaps your custom card is able to auto-maintain the entity-list (I just didn't understand it), or.... ?

**Comment by maxwroc** [comment]
Please check filters documentation (https://github.com/maxwroc/battery-state-card#filters) you can specify rules to automatically add entities. There are some examples at the bottom of the page

**Comment by maxwroc** [comment]
Closing for now, please reopen if the above didn't solve your problem
