### ISSUE TITLE
Tap Feature

### ISSUE THREAD

**Issue by 03397** [maxwroc/battery-state-card#36]
I do not know if this is feasible or not but it will nice to see the same colors when your tap to the entity
See  my picture, colorful but when tap it displays the default

![image](https://user-images.githubusercontent.com/6150853/80921014-30a80400-8d7c-11ea-98de-89396a41d2c5.png)

**Comment by maxwroc** [comment]
Sorry, it is not possible. This is a generic more-info popup and I don't have control over its UI
