### ISSUE TITLE
Default values for charging-state and tap-action.

### ISSUE THREAD

**Issue by floli** [maxwroc/battery-state-card#365]
Hello,
it seems that there are no default settings for the `tap-action` and for the `charging-state`. I wonder if there are no good defaults that at least cover *most* use cases.

* For `tap-action` imho it makes sense to have the same action as the entities card, i.e., show the detailed information about the entity.
* For the `charging-state`, I wonder if there a convention how to relate the reporting of the charging state to the the entity? I use the Android HA companion app and have a `binary_sensor.<entitiy>_is_charging` and a `sensor.<entitiy>_battery_state` that can have the value `charging`. Is that fundamentally different for other devices? As this comes from the official app, I would propose to use that as a default.

What do you think?

**Comment by maxwroc** [comment]
That is actually a very good idea. I was thinking before about minimizing the need of custom configuration. I think that for v3 I will do the automatic battery entity search, sorting, grouping (in case of larger number of entities present) + the above what you have proposed
