### ISSUE TITLE
Hide the battery state values or show them as secondary info

### ISSUE THREAD

**Issue by rathmannm** [maxwroc/battery-state-card#381]
It would be nice to have a way to actually hide the battery state values (or alternatively only show them as secondary info)? This would give more space for the actual name of the entity and the battery level as such is indicated by the color.

![image](https://user-images.githubusercontent.com/7580841/149575306-01e4fc3c-02ae-4014-9827-0c5b7560799d.png)

**Comment by maxwroc** [comment]
The idea in general is good but closing it for now

In v3 it will be possible to show the state in the secondary info and removing the state can be achieved via card_mod (not a perfect solution but should work).
