### ISSUE TITLE
Card currently prioritizes higher the “battery_level” attribute over the state - even when state is battery percentage

### ISSUE THREAD

**Issue by dangel666** [maxwroc/battery-state-card#382]
**Describe the bug**
It's currently not possible to force the card to display the state instead of searching for (for example) battery_level in preference.  This is an issue where the state is indeed the battery percentage and battery_level (for example) is in fact a string e.g. "one third" "two thirds" etc.

**How to reproduce**
I'm using the wiser integration which has recently been updated and now shows the TRV battery percentages through the state attribute directly.  In this case I'm unable to get the card to display percentage.

**Expected behavior**
Perhaps have a flag to force the card into accepting state as being the percentage value or ignore the search?

# please paste here your card config
type: custom:battery-state-card
title: Battery Status
entities:
  - entity: sensor.wiser_itrv_bathroom_battery
    name: Bathroom Radiator
    secondary_info: battery_level

**Screenshots**
![image](https://user-images.githubusercontent.com/44338896/149652715-837e24d4-65e1-4bea-b952-cb8652904370.png)

The above shows what happens with my current config.

**Version**

v2.1.0

**This is how the device presents in HA**

![image](https://user-images.githubusercontent.com/44338896/149652791-bff6ec4c-7ba7-4581-b2f9-7372ada44cff.png)

**Comment by chris-github1975** [comment]
I agree with dangel666. I believe the search for battery_level attribute should be optional and the actual device state be the default.

**Comment by estiens** [comment]
I attempted a simple first pass fix of this that seems to work pretty well for me - feel free to pull it down and see if it addresses any of your issues

**Comment by maxwroc** [comment]
Fixed in v2.1.1

**Comment by dangel666** [comment]
Thanks guys - can confirm it's working perfectly!

![image](https://user-images.githubusercontent.com/44338896/150674006-c548575a-1832-483a-978e-62db34e084dd.png)

**Comment by chris-github1975** [comment]
A thumbs up from me too. Many thanks for the update.

________________________________
