### ISSUE TITLE
Convert sensor values as keywords to numbers, colors

### ISSUE THREAD

**Issue by mdzmdz** [maxwroc/battery-state-card#387]
**Is your feature request related to a problem? Please describe.**
My battery sensor does not return number, but values as keywords like high, low, medium

**Describe the solution you'd like**

1. Allow colors on specific value (for example high as green, low as red), OR
2. convert keywords to values (for example high convert to 80 and use colors as on other sensors)

**Additional context**
![image](https://user-images.githubusercontent.com/94713948/150764839-ea5b7177-db50-4484-b4ca-ec55ed50f59d.png)

**Comment by maxwroc** [comment]
The second one is possible already. Please look at the doc and state_map setting

**Comment by mdzmdz** [comment]
> The second one is possible already. Please look at the doc and state_map setting

Does it really work? I see no effect.

  - entity: sensor.motion_sensor_battery_state
    name: Pohybový senzor 2
    state_map:
      - from: High
        to: 75
      - from: Medium
        to: 50
      - from: Low
        to: 25

**Comment by maxwroc** [comment]
Please reopen if it didn't solve your problem
