### ISSUE TITLE
Bug With Ring Spotlight Camera With Dual Batteries

### ISSUE THREAD

**Issue by nocturnalarchives** [maxwroc/battery-state-card#395]
The Ring Spotlight Camera has two battery slots, when you use two batteries, the percent charged can be as high as 200%, this breaks the color coding.

You can reproduce the condition by having a battery charge level of 100%.

Is it possible to update the code so it shows as green?

I attached a screenshot, if you need any more information let me know.

![ha-battery-levels-error](https://user-images.githubusercontent.com/64667374/152662464-c40be8c8-365f-44b9-9e68-d7778fc28e5f.jpg)

**Comment by maxwroc** [comment]
If the value range is always 0 - 200 as it is a sum of two battery states you can use the `multiplier` option to make it 0 - 100.

```yaml
multiplier: 0.5
```

Does it solve your problem?

**Comment by maxwroc** [comment]
Closing for now - please reopen if the above doesn't solve your problem
