### ISSUE TITLE
Blank page without any information

### ISSUE THREAD

**Issue by maxifly** [maxwroc/battery-state-card#398]
**Describe the bug**
Crate a simple yaml  like the first example in read.me
In lovelice i see a blank page

**How to reproduce**

**Expected behavior**

**YAML configuration**
```yaml

# please paste here your card config

    type: custom:battery-state-card
    title: "test"
    entities: 
      - entity: sensor.bedroom_atmosphere_battery
      - entity: sensor.bedroom_button_battery
      - entity: sensor.bedroom_switch_battery
      - entity: sensor.bedroom_motion_battery
      - entity: sensor.bedroom_motion2_battery
      - entity: sensor.bedroom_illuminate_battery

or this configuration (same effect):
    type: custom:battery-state-card
    title: "test"
    entities: 
      - sensor.bedroom_atmosphere_battery
      - sensor.bedroom_button_battery
      - sensor.bedroom_switch_battery
      - sensor.bedroom_motion_battery
      - sensor.bedroom_motion2_battery
      - sensor.bedroom_illuminate_battery

**Screenshots**

**Version**
v2.2.1 (in old version i have same problem)

**Comment by maxwroc** [comment]
Do you see a blank box only in preview area when you are adding the card? Or is it on the page too (once you hit the add/save button? What if you refresh/reload the page?

**Comment by maxwroc** [comment]
Are there any errors in the browser dev console (dev tools)?

**Comment by maxifly** [comment]
![image](https://user-images.githubusercontent.com/2596114/152989723-b8f73702-0533-40c5-8aa1-5995a5417c2e.png)

**Comment by maxifly** [comment]
![image](https://user-images.githubusercontent.com/2596114/152994472-3f95cad9-ac03-42c7-9a14-8e9897852447.png)

**Comment by maxifly** [comment]
![image](https://user-images.githubusercontent.com/2596114/152994783-ff58bc99-b71e-49c0-bc64-55ca15100948.png)

**Comment by maxifly** [comment]
I solved.
I add minus before "type".

  - type: custom:battery-state-card
    title: "test"
    entities: 
      - sensor.bedroom_atmosphere_battery
      - sensor.bedroom_button_battery
      - sensor.bedroom_switch_battery
      - sensor.bedroom_motion_battery
      - sensor.bedroom_motion2_battery
      - sensor.bedroom_illuminate_battery
