### ISSUE TITLE
Editor not working correctly

### ISSUE THREAD

**Issue by royto** [maxwroc/battery-state-card#4]
In the editor, entities are not displayed (no name, battery level is 0)

![image](https://user-images.githubusercontent.com/6990995/80318540-25e4f080-880b-11ea-9ff5-0eea5f61252e.png)

But it works well in normal mode

![image](https://user-images.githubusercontent.com/6990995/80318558-4b71fa00-880b-11ea-8112-8777efb305d5.png)

So it's hard to define the card

Version Used
Home Assistant:  0.108.6
Frontend: 20200407.2

**Comment by maxwroc** [comment]
I'll take a look what is going on. Thanks!
