### ISSUE TITLE
RSSI card shows Battery for BLE device 

### ISSUE THREAD

**Issue by Psytoshgen** [maxwroc/battery-state-card#401]
**Describe the bug**

rssi shows batterry state
**How to reproduce**

BLE device Xiaomi MJYD02YL found over Passive BLE monitor Intergration provides both Batterry and rssi information
got two entities 
sensor.ble_battery_b460ed979297 (now its 50%)
sensor.ble_rssi_b460ed979297 ( -67 dBm)

**Expected behavior**

Well, i just wanted to see right numbers =)
The good part is that if I try to insert RSSI entity to Battery card its autochanges to battery entity

**YAML configuration**
```yaml

# please paste here your card config

```

**Screenshots**

![1](https://user-images.githubusercontent.com/94195788/153122283-4cf90a62-0350-4f46-bca7-e2f07e947e03.jpg)
![2](https://user-images.githubusercontent.com/94195788/153122296-8f598418-3fbd-4cb9-9c6e-7dc365f05e71.jpg)
![3](https://user-images.githubusercontent.com/94195788/153122312-6099a150-24ff-484a-9bad-083fb580052e.jpg)

**Version**

last

all updated to last (beta channel)

**Comment by Psytoshgen** [comment]
![B38858A9-6222-493F-89C8-8BEF6F3AC786](https://user-images.githubusercontent.com/94195788/153451178-1d2d452b-dd6c-49da-8a63-25dbbcf58491.png)
![5D419C0E-7C19-4EBE-887D-74AA58ED74BF](https://user-images.githubusercontent.com/94195788/153451196-0fad4a97-69b9-423c-b7b6-75d7c805e3f3.png)

**Comment by maxwroc** [comment]
Reoppening it as it make sense to have a way to disable this logic

**Comment by Psytoshgen** [comment]
Hi! Thank you for support again, also I found that gradient didn’t work with lqi all signals is  grey, maybe it’s result that it’s shows as negative

**Comment by greendog99** [comment]
Also interested in this. I have Xiaomi temperature/humidity sensors all over the place and hoped to use this to show room temperatures with color-coded icons. The "state" of `sensor.living_room_temperature` contains the temp, but the card ignores that and show's the sensor's battery level since that's one of the attributes. Totally understand that this is primarily a battery card... but it's so close to being useful in so many other ways :-). Either way, thank you for the card! I love using it for batteries too...

**Comment by airampg** [comment]
Hi! Thanks for this awsome card! I was wondering whether any progress has been made on this? Thanks!

**Comment by maxwroc** [comment]
Ok I think that I have something what will work for you (will be available in v3)

![image](https://github.com/maxwroc/battery-state-card/assets/8268674/f3416b14-6787-4f15-8312-70170b107684)

**Comment by maxwroc** [comment]
I think I was reading and thinking about too many enhancements/issues at the same time and I confused this one with the one which was related. Anyway your problem will be solved when you add `non_battery_entity: true` in the card/entity configuration. This way you're disabling lookup on attributes to get the state

**Comment by maxwroc** [comment]
I've added one more feature which you may find useful. More details here #586
