### ISSUE TITLE
Entity reporting >100%

### ISSUE THREAD

**Issue by Pasod** [maxwroc/battery-state-card#42]
This is probably a rare occurrence and perhaps only related to Rings "Spotlight Cam Battery" but this device reports up to 200% of battery and the reason is because it supports up to two batteries.

Attached is an image of my Spotlight Cam Battery.
The fact that its reporting more than 100% is fine but when it does its not showing a battery icon.
It would be great if the default threshold for a green icon would be set to a large value, for example "If value is less or equal 1000 the color will be green".

If perhaps the values on how to display the icon for filled battery is calculated on a value between 0-100 then at least show a green icon with full battery for anything that is greater than 100% and once its drops below 100% then display the battery state as for any type of entity.

If there is a trick to get this to show an icon I have not yet found one. Perhaps this could be worked around with a template sensor that calculates a percentage out of 200 but would be cleaner to have this plugin to handle that instead.

![image](https://user-images.githubusercontent.com/1451428/81004478-5c8ebc80-8e44-11ea-8d30-3fc2801059b5.png)

**Comment by maxwroc** [comment]
Please take a look at the documentation - search for multiplier. If you set it to `0.5` it should do the trick.

**Comment by Pasod** [comment]
Absolutely perfect, completely missed that even though I read through the docs.
Thanks man, works perfectly!
![image](https://user-images.githubusercontent.com/1451428/81005548-07ec4100-8e46-11ea-9fc9-a09b100b9d70.png)
