### ISSUE TITLE
Use a different entity as secondary_info

### ISSUE THREAD

**Issue by quentinus95** [maxwroc/battery-state-card#421]
Using a different entity as `secondary_info` would be nice. I have two entities, one with the battery level, and a second one indicating if the device is on power saving.

It would be practical to be able to display "Power saving" next to the device name when power saving is enabled.

**Comment by michaelblight** [comment]
+1 for me, as I have the date the battery was replaced is in another entity. I also noticed a minor bug where if you use a binary attribute as the secondary info, true shows as "52 years ago", and false shows the attribute name as text. I'm assuming this is 1st Jan 1970.

**Comment by maxwroc** [comment]
It is actually implemented already and will be available in v3. But I cannot give you any ETA for release, sorry

**Comment by RoboMagus** [comment]
Very much looking forward to this as well!

I was planning on coding up a template card in order to show secondary info on when the battery was last changed, but being able to do so from within the battery-state-card would be far better 😃

**Comment by PsY4** [comment]
As it seems to be available on v3.0, how do you achieve this ?

**Comment by maxwroc** [comment]
https://github.com/maxwroc/battery-state-card#keyword-string-kstring
