### ISSUE TITLE
Surface battery type for non-rechargeable batteries

### ISSUE THREAD

**Issue by misberner** [maxwroc/battery-state-card#423]
**Is your feature request related to a problem? Please describe.**
I use this dashboard card only for battery states that require my attention. For non-rechargeable batteries, "attention" means to go and buy a new battery of a specific type (e.g., CR2032 or 4xAA). However, that information is nowhere to be found - I have to look up the device model to determine the battery type. I could rename the device to include the battery type, but that's (a) ugly and (b) cumbersome if I have a lot of devices of the same model (e.g., door/window sensors).

**Describe the solution you'd like**
It would be great if there was a registry (YAML would suffice) mapping device models to battery types. This registry should ideally be pre-populated for common devices (Aqara mini, Hue switch, ...), but also extensible or overridable by the user. The override functionality could also be used for devices that can be used with rechargeable or non-rechargeable batteries, e.g., the Nuki Smart Lock. If I use power packs with all my Nukis, I could just override the battery type from "4xAA" to "USB-C charge".

**Additional context**
This is an awesome card, thanks for creating it!

**Comment by maxwroc** [comment]
Interesting idea

**Comment by GaryGSC** [comment]
In the meantime, I opened my devices to inspect their batteries and then used `secondary_info` to accomplish this:
![image](https://user-images.githubusercontent.com/7625337/183735633-627759f5-5b23-4adc-9979-4bcc4055d3c5.png)

**Comment by maxwroc** [comment]
Entities don't have the info about the device... I wonder if it's possible to extract is it somehow from the HA...

**Comment by kaphacs** [comment]
Under "Developer tools" in HA, battery attributes show "battery_size" and "battery_quantity".

Examples:

- battery_size: AAA
- battery_quantity: 2

or 

- battery_size: CR2032
- battery_quantity: 1

Would these be usable as-is as the 'secondary_info'?

**Comment by maxwroc** [comment]
In v3 you can add to secondary_info everything what is available in entity states (any entity and attributes).

For example the below will print "Battery type: AAA":
`secondary_info: "Battery type: {attributes.battery_size}"`

Example of printing data from the other entity
`secondary_info: "Battery type: {sensor.other_entity_id.attributes.battery_size}"`
