### ISSUE TITLE
Clickable link to entity history

### ISSUE THREAD

**Issue by janjbrand** [maxwroc/battery-state-card#43]
I really like the battery state card, thanks for your effort.

For a regular 'entities'-element, it is possible to click on an entity. In that case the 'history graph' for that entity is shown in a pop-up screen (see example below). Is it possible to add this feature to the battery entity card? Right now it is not possible to see directly how battery levels have evolved (apart from adding extra cards).

![afbeelding](https://user-images.githubusercontent.com/54683154/81293160-24b68d80-906d-11ea-8cbe-3861bdbeb3e9.png)

**Comment by maxwroc** [comment]
There is tap_action property which you can define on card or entity level. When you do it you are able to click on entity on the card. You can have couple of actions - if you want to see the above popup you need to add:
```yaml
tap_action:
  action: more-info
```
