### ISSUE TITLE
Tado Battery

### ISSUE THREAD

**Issue by McFarTech** [maxwroc/battery-state-card#434]
Hi Guys. 

I have Tado TRV and the batteries in them are not reported at a % level.  They report as Normal or Low

How can I have the battery icon show as green for Normal and Red for Low? 

Many thanks

**Comment by maxwroc** [comment]
Look at the state_map setting, I think there are even examples

**Comment by McFarTech** [comment]
Hi. Sorry i should have said i have used the state_map example but this is not producing the results I want. I have a TRV battery that is showing as Low but using the state_map is showing as green

**Comment by maxwroc** [comment]
First of all: why you haven't used the "question" template? In this template you have a list all of the details which can be helpful to provide answer/solution. Now I know nothing except that it doesn't work for you

**Comment by maxwroc** [comment]
Noticed now that someone suggested you (on HA community forum) what was the mistake in your configuration.

**Comment by McFarTech** [comment]
First of all: First time posting here and wont make the same mistake again.  Sorry if I got the initial post wrong!
