### ISSUE TITLE
show device's area as secondary info

### ISSUE THREAD

**Issue by toshymaeda** [maxwroc/battery-state-card#440]
Show the device's area - or if not possible, at least the groups containing the entity - as the secondary info on the card.

Context:
In my case, the entity name not always give me the necessary information to accurate "define" the correct sensor - especially now with the more use of HA devices. As an example, I have a device named "Weather Sensor 01", containing 4 entities: pressure, humidity, temperature and battery (with these names defined).

**Comment by maxwroc** [comment]
Oh forgotten to close it. This is now possible: `"{area.name}"`

You can explore the other properties which can be shown by adding in your card config  `debug: true` or `debug: sensor.specific_entity_id`
