### ISSUE TITLE
Color thresholds for values over 100

### ISSUE THREAD

**Issue by nabahr** [maxwroc/battery-state-card#460]
I use this card for connection quality for zigbee devices, not the intended use I know but it does work quite well with one issue.
The value range is up to 255, but all values over 100 use the default color and don't respect the color threshold settings of the card.
Setting a color gradient also only applies to values <=100

**Comment by maxwroc** [comment]
you can use the `multiplier` setting to adjust the values - scale them to be in 0-100 range then everything should work. Of course the disadvantage is that the displayed values will change but...

**Comment by programmdesign** [comment]
👍 +1 for adding this feature and/or to extend the scope of entire project to not just cover batteries, but to be able to manage various sensors of the same kind with smart filters, customs thresholds, and more.

**Comment by maxwroc** [comment]
In v3 you can easily convert random values to percentages and colors till work. Check other examples section in doc
