### ISSUE TITLE
"Confirmation" option for tap_action

### ISSUE THREAD

**Issue by michaelblight** [maxwroc/battery-state-card#472]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I'm looking to use `tap_action` to reset the date a battery was last charged in Grocy. To avoid unintented clicks, it would be great if this card supported "confirmation" under "tap_action" like the default does for HA (see https://www.home-assistant.io/dashboards/actions/#options-for-confirmation). 
**Additional context**

**Comment by maxwroc** [comment]
Thanks for the suggestion. Yes definitely it make sense

**Comment by maxwroc** [comment]
Closing as this will be covered by #691
