### ISSUE TITLE
Show "binary" battery state

### ISSUE THREAD

**Issue by smartroad** [maxwroc/battery-state-card#479]
I have a couple of battery powered zigbee devices that just report their battery status when they are "low" (so false when battery is good and true when battery is high) and not as  %. Is there a way to display these so that they show a green battery symbol when the battery is ok and a red one when the battery is low?

**Comment by maxwroc** [comment]
Check state_map in documentation. There should be even done examples

**Comment by smartroad** [comment]
I saw that and totally misread its use 🥴 thanks for the reply!
