### ISSUE TITLE
"Unknown" state is shown as zero

### ISSUE THREAD

**Issue by maorcc** [maxwroc/battery-state-card#5]
![image](https://user-images.githubusercontent.com/255973/80319981-35b90080-881c-11ea-97a1-adb38c8ef75a.png)

**Comment by SeLLeRoNe** [comment]
I would sugget sto set it to gray (128,128,128), I used it that way:
![image](https://user-images.githubusercontent.com/9599441/80361914-ff15d100-8881-11ea-9c76-656dd39aec1a.png)
