### ISSUE TITLE
How to include Nuki lock?

### ISSUE THREAD

**Issue by GLehnhoff** [maxwroc/battery-state-card#519]
**I would like to know how to include my Nuki Lock. It has no battery entity id, only an attribute**
The "entity_id: lock.haustur" hat an attribute "battery_critical: false|true"

![grafik](https://user-images.githubusercontent.com/5453201/208443930-898059a5-1233-46e0-be30-9faf67d32b2a.png)

**Current card config:**

```type: custom:battery-state-card
title: Gerät (bald) nicht erreichbar
sort_by_level: asc
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
tap_action: more-info
filter:
  include:
    - name: entity_id
      value: '*_battery_level'
    - name: attributes.device_class
      value: battery
  exclude:
    - name: state
      value: 2
      operator: '>'
    - name: state
      value: Status unbekannt
      operator: '='
state_map:
  - from: 'off'
    to: 100
  - from: false
    to: 100
  - from: 'on'
    to: 5
  - from: true
    to: 5
  - from: unknown
    to: Status unbekannt
  - from: unavailable
    to: 0
bulk_rename:
  - from: Battery
    to: ''
  - from: battery
    to: ''
  - from: Batterie
    to: ''
  - from: level
    to: ''
  - from: Percent
```

**Version**
always newest version

**Comment by maxwroc** [comment]
You need to add this entity explicitly to the `entities` collection and specify that the value should be taken from this specific attribute then the state map which you have there should work e.g.

```yaml
entities:
  - entity: lock.haustur
    attribute: battery_critical
state_map:
  - from: false
    to: 100
  - from: true
    to: 5
```

Please close if this solves your problem. BTW usually it's quicker to look for a solution on community forum

**Comment by GLehnhoff** [comment]
Many, many thanks to you, @maxwroc, it works like a charm.
