### ISSUE TITLE
Empty "hidden" card still takes up space

### ISSUE THREAD

**Issue by ScottG489** [maxwroc/battery-state-card#521]
**Describe the bug**
Card still takes up a small amount of space when it should be hidden. I believe we should apply a `display: none` style to the card. It looks like this was partially implemented with #360 to fix #359 (where I left a related comment).

**How to reproduce**
Create a card that has no displayed battery entities. It takes up a small amount of space due to margins (see screenshots below).

**Expected behavior**
Card should not only be hidden, but take up no space.

**YAML configuration**
N/A

**Screenshots**
`auto-entities` for comparison:

<img width="421" alt="Screen Shot 2022-12-23 at 12 53 57 PM" src="https://user-images.githubusercontent.com/910809/209383649-0721c45a-8798-4688-a759-bdb7b849fd74.png">

You can see the battery card next to another card with the element highlighted in dev tools:

<img width="403" alt="Screen Shot 2022-12-23 at 12 55 11 PM" src="https://user-images.githubusercontent.com/910809/209384008-3e385e44-f0fc-4596-97a9-322ab6c101d8.png">

That part highlighted in orange is due to a 4 pixel margin on the top and bottom. Small nitpick of course, but it adds a noticeable gap when nested between other cards.

**Version**
v2.1.1

**Comment by maxwroc** [comment]
Thanks for details. Indeed this could be fixed/improved

**Comment by maxwroc** [comment]
Fixed in v3
