### ISSUE TITLE
display color icon that has values >100

### ISSUE THREAD

**Issue by nebbiadigiorno** [maxwroc/battery-state-card#530]
i can't figure out if is possible to give a certain color for identity thats has values bigger than 100.
I am using this card to display the watt of some smart plug. The value more than 100 doesn't change the icon color

**Comment by storebatfar** [comment]
I have the same issue and question.
I have used the card for listing device link quality. When a device has a link quality above 100 lqi, the color does not change.

**Comment by nebbiadigiorno** [comment]
no ideas?

**Comment by Murada99** [comment]
Same problem, using it with my smart plugs to follow power consumption but above 100w, I can't change the colors.

**Comment by nebbiadigiorno** [comment]
still no answer?
