### ISSUE TITLE
Mouse Pointer dosnt change

### ISSUE THREAD

**Issue by therealhalifax** [maxwroc/battery-state-card#536]
**Describe the bug**
In case of "tap_action: more-info" the mouse pointer dosnt change to finger in Chrome browser

**How to reproduce**
Set "tap_action: more-info" and hover the mouse on an entity

**Expected behavior**
mouse pointer shall change to "finger"

**YAML configuration**
```yaml

# please paste here your card config
type: custom:auto-entities
card:
  type: entities
  title: Geräte
filter:
  include:
    - entity_id: sensor.robi_battery_level
      options:
        type: custom:battery-state-entity
        tap_action: more-info
        color_gradient:
          - '#ff0000'
          - '#ffff00'
          - '#00ff00'
    - entity_id: sensor.ups_battery_charge
      options:
        type: custom:battery-state-entity
        tap_action: more-info
        color_gradient:
          - '#ff0000'
          - '#ffff00'
          - '#00ff00'
    - entity_id: sensor.handy*battery*
      options:
        type: custom:battery-state-entity
        tap_action: more-info
        color_gradient:
          - '#ff0000'
          - '#ffff00'
          - '#00ff00'
    - entity_id: sensor.*battery_charge_remaining_percentage
      options:
        type: custom:battery-state-entity
        tap_action: more-info
        color_gradient:
          - '#ff0000'
          - '#ffff00'
          - '#00ff00'
  exclude:
    - entity_id: sensor.*temperature
    - entity_id: sensor.*state
    - entity_id: sensor.handy*battery*
      state: unavailable
    - entity_id: sensor.*battery_charge_remaining_percentage
      state: unavailable
sort:
  method: state
  numeric: true
  reverse: false

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->

**Version**
v2.1.1

**Comment by maxwroc** [comment]
If you have a repro without auto-entities card please let me know (I don't). If this is broken with auto-entities only then it will be closed as "won't-fix".

BTW the same result you should be able to achieve with battery-state-card itself - without auto-entities card. There are filters available here as well although note that they are not being configured in the same way so you cannot just copy-paste them

**Comment by therealhalifax** [comment]
@maxwroc Before using your card I was with the "Battery Entity Row" in combination with the auto entities. There the mouse hover was fine. You are right, if I remove the auto entities the mouse hover works also with your card. But this filter function works only as stand alone card and not inside entities card, which will require card-mod to combine several "lists" of battery entities in one card.

The reason is that I have a lot of battery entities and I want to show only that with a low level, the others are "hidden" in a drop down list. And others show the state as binary_sensor and will be grouped inside another list in the same card.

**Comment by scorfman** [comment]
@therealhalifax I think you have just a syntax error. Use the following:
`tap_action:
  action: more-info`

You can set this for all entities by using tap-action as I show in the following code snippet so you don't have to set it for each entity: 
`type: custom:battery-state-card
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
secondary_info: last_updated
tap_action:
  action: more-info`

**Comment by maxwroc** [comment]
Actually it turned out there is a bug but it occurs only when battery-sate-entity is used (not battery-state-card). I'll fix it
https://github.com/maxwroc/battery-state-card/issues/503
