### ISSUE TITLE
Ability to change the secondary_info text color

### ISSUE THREAD

**Issue by SeLLeRoNe** [maxwroc/battery-state-card#56]
**Is your feature request related to a problem? Please describe.**
The secondary_info color text differ from the "main" text, it would be nice if we can cutomize the color (or if can be set as the main color by default)

**Describe the solution you'd like**
Ability to have the secondary_info text color to match the main text color

**Additional context**
![image](https://user-images.githubusercontent.com/9599441/82367330-eb3e3480-9a13-11ea-827c-fe89987bb3f5.png)

![image](https://user-images.githubusercontent.com/9599441/82367374-fabd7d80-9a13-11ea-8410-74a6280ffbee.png)

**Comment by maxwroc** [comment]
FYI this is a standard color for secondary info text. But I'll think about making it customizable

**Comment by SeLLeRoNe** [comment]
Thanks for the info, didn't know that :)

I assumed, due to the other card color, that it was driven by the card itself :)
If the option to define the text color can be implemented would be nice, otherwise no problem :)

**Comment by maxwroc** [comment]
You can adjust colors via custom styles in v1.4.0

To control color of secondary text use the following:
```yaml
style: |
  .entity-row .secondary {
    color: red;
  }
```
