### ISSUE TITLE
Collapse values over a certain treshold

### ISSUE THREAD

**Issue by Giom-V** [maxwroc/battery-state-card#568]
**Is your feature request related to a problem? Please describe.**
I love the card because it gives me a quick overview of my most critical batties to change/charge. But also because I can get a view of all of them if I want to. The problem is I don't always cwant to see them all so I'd love to be able to set a treshold so that I see the entites that are under that value, and the ones over if would be under the collapsed part.

**Describe the solution you'd like**
I think the best solution would be a "collapse_treshold" value that we could use to set a certain treshold.

**Additional context**

**Comment by RedNo7** [comment]
this works in v3.0
```yaml
    collapse:
     - name: 'x{count} at {min}% min'
       min: 40
```

**Comment by maxwroc** [comment]
TBH there were no changes here between v2 and v3 - it was possible to do it before too :)

**Comment by Giom-V** [comment]
Amazing, thanks!
