### ISSUE TITLE
Add option to capitalize after bulk rename

### ISSUE THREAD

**Issue by igorsantos07** [maxwroc/battery-state-card#570]
**Is your feature request related to a problem? Please describe.**
Sort of.
For some languages, the "battery" part on the entity name you want to get rid off isn't at the end, and thus you end up with some entities in lower case. E.g. "Bateria do sensor" becomes "sensor", while "Sensor battery" would show "Sensor", as some other non-renamed entities.

**Describe the solution you'd like**
Add a `bulk_rename_capitalize: true` option that would set the first letter of renamed entities to be capitalized, so it leaves all entity names in the same capitalization format

**Comment by igorsantos07** [comment]
Actually, I think I can code the feature, if you agree with the idea :)

I guess I only need to grab the config and capitalize it [here](https://github.com/maxwroc/battery-state-card/blob/d4ac1d54e4957fa93edfd7b19386a50075e667b6/src/custom-elements/battery-state-entity.ts#L154-L163, right? And document the new option, obviously.

**Comment by maxwroc** [comment]
Thanks for the suggestion. I think it make sense and feel free to send PR!

> I guess I only need to grab the config and capitalize it here, right? And document the new option, obviously.

yup

**Comment by maxwroc** [comment]
@igorsantos07 release v3 will happen in next few days. Code in the master branch is already a v3 version.

Now the file which you would need to touch is here
https://github.com/maxwroc/battery-state-card/blob/master/src/entity-fields/get-name.ts

If you want to add it to the v3.0.0 it is the best time to do it. If you won't be able to do it I will probably do it myself but in the next releases.

**Comment by maxwroc** [comment]
Will be available in v3.1

**Comment by igorsantos07** [comment]
Sorry! Life is a mess and I never got the previous messages. Thanks for being a great OSS developer, sir! And happy holidays for you!
