### ISSUE TITLE
Help for my batteries in my map 

### ISSUE THREAD

**Issue by unecc** [maxwroc/battery-state-card#572]
Hi, how can i add your fantastic program for check battery of my entities in this part of my map?

![image](https://github.com/maxwroc/battery-state-card/assets/134554559/1c4e6031-bb6f-4fd5-a0c6-885e601fdde6)

**Comment by maxwroc** [comment]
Sorry but I have no idea what are you using to display the floorplan and such questions should be rather asked somewhere else (e.g. repo of the floorplan card you use or the related thread on HA forum). I'm afraid I won't be able to help here
