### ISSUE TITLE
Is there an issue with the release as 3 isn't showing

### ISSUE THREAD

**Issue by lloydbayley** [maxwroc/battery-state-card#583]
Version number on release is still 2.1.1 yet the readme speaks of v3.
Was wondering why I couldn't use the {states} etc stuff.

Have I missed something or has github not pushed it to production?

**Comment by maxwroc** [comment]
Sorry about the confusion... v3 is not published yet but it will happen in next few days so please stay tuned

If you need access to the old docs here is the link:
https://github.com/maxwroc/battery-state-card/tree/v2.1.1

**Comment by lloydbayley** [comment]
Ahh...That makes sense.
I was battling for a good hour trying to work out why modifier code wasn't being interpreted.
Nevermind.
Thanks for the update. Will await the release.

**Comment by lloydbayley** [comment]
Closing as "Coming Soon!" :)
