### ISSUE TITLE
Respect display precision set for entity in HA

### ISSUE THREAD

**Issue by JaroSu** [maxwroc/battery-state-card#595]
**Describe the bug**

The card doesn't use the precision settings. 

**How to reproduce**

Change display precision of battery entity - no effect on card.

**Expected behavior**

Display entity value with user precision

**Comment by maxwroc** [comment]
It's not a bug. Card doesn't use the precision set for the entity in HA. I need to find out how to get it from hass.

Changing this issue to enhancement.

You can set the precision by using the `round` option: https://github.com/maxwroc/battery-state-card#common-options
