### ISSUE TITLE
Values are no longer being sorted 

### ISSUE THREAD

**Issue by GRClark** [maxwroc/battery-state-card#607]
After last update values are no longer being sorted even though card code hasn’t changed.  Looking to see why this may have happened and/or get some advice how to fix.  Looking for ascending battery values.  

Here is code:

`type: custom:battery-state-card
title: Batteries
sort_by_level: asc
entities:
  - entity: sensor.doorbell_battery_level
    format: precision0
  - entity: sensor.living_room_window_left_battery
  - entity: sensor.living_room_window_right_battery
  - entity: sensor.screen_door_battery
  - entity: sensor.front_door_battery
  - entity: sensor.refrigerator_battery
  - entity: sensor.bedroom_door_battery
  - entity: sensor.entrance_multi_sensor_battery
  - entity: sensor.hallway_motion_sensor_battery_level
  - entity: sensor.bedroom_motion_sensor_battery_level
  - entity: sensor.bedroom_button_battery
  - entity: sensor.living_room_button_battery
  - entity: sensor.samjin_button_battery_2
  - entity: sensor.siren_downstairs_battery_level
  - entity: sensor.siren_upstairs_battery
  - entity: sensor.bedroom_window_right_battery
  - entity: sensor.bedroom_window_left_battery
  - entity: sensor.outdoor_govee_battery
  - entity: sensor.downstairs_govee_battery
  - entity: sensor.upstairs_govee_battery
 `

Here is how card looks.  

![IMG_8013](https://github.com/maxwroc/battery-state-card/assets/5118059/60ce7ee0-57f5-44f5-9535-345f632f90e4)

Using version 3.0.1

**Comment by maxwroc** [comment]
Please take a look at the "breaking changes" section in documentation
