### ISSUE TITLE
Allow to use entities from all of the available domains in KString

### ISSUE THREAD

**Issue by digi303** [maxwroc/battery-state-card#611]
Thank you very much for the great card.

I enter the battery replacement date manually via input.datetime
Is it somehow possible to display this value as secondary-info?

Thanks for an answer

**Comment by maxwroc** [comment]
No, it is not possible at the moment - you can use entities from "sensor" and "binary_sensor" domains only e.g.
`secondary_info: "{sensor.other_entity.state}"`

But TBH this limitation doesn't make sense and it will be very easy to change it.
https://github.com/maxwroc/battery-state-card/blob/master/src/rich-string-processor.ts#L4C1-L4C32

Changing it to feature request.

PS
Please next time try to put few more details in the issue title

**Comment by maxwroc** [comment]
It's just a matter of extending the following list by valid entity domain names:
https://github.com/maxwroc/battery-state-card/blob/master/src/rich-string-processor.ts#L4
