### ISSUE TITLE
Support for hold_action

### ISSUE THREAD

**Issue by RoboMagus** [maxwroc/battery-state-card#626]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a more easy to use battery management solution. This battery state card already provides great overview of all the states of battery powered devices, but for my usecase I'd also like to track when the batteries were last changed.

The tracking I need is already in place, but it'd be a great addition if we could register actions to a `hold_action` as well. In my case triggering a service that updates the last battery change time for the entity the action was called on.

**Describe the solution you'd like**

An implementation of the `hold_action`, similar to `tap_action` that allows us to register additional actions to entities, such ass calling a service. Ideally with the option to retrieve the entity config / entity_id (inspired by the entity-options of [thomasloven/lovelace-auto-entities](https://github.com/thomasloven/lovelace-auto-entities?tab=readme-ov-file#entity-options))

**Additional context**

**Comment by maxwroc** [comment]
Closing as this will be covered by #691
