### ISSUE TITLE
Allow to use entities from all of the available domains in KString (Version 3.1.0)

### ISSUE THREAD

**Issue by digi303** [maxwroc/battery-state-card#627]
Hello Maxwroc,

Thank you very much for realising the idea with Secondinfo.
Unfortunately, I am still unable to integrate statuses from other entitys in version 3.1.x. Sensor... or binary_sensor... works perfectly. Everything else still does not. 

Am I doing something wrong?
![view](https://github.com/maxwroc/battery-state-card/assets/94383598/147b3809-e33f-4281-bc38-19a3e2e121bd)
![code](https://github.com/maxwroc/battery-state-card/assets/94383598/080cca9e-5e6a-425b-b36f-f138d059311b)

**Comment by maxwroc** [comment]
Sorry but I have no repro - I have tested in on one of the light entities and everything works fine.

Can you please double check if the light entity name is correct? And what is it's exact state?

**Comment by maxwroc** [comment]
Closing for now. Please reopen once you answer
