### ISSUE TITLE
Filter out spurious binary sensors (e.g. for Sonoff TRVZB)

### ISSUE THREAD

**Issue by plush** [maxwroc/battery-state-card#646]
Sonoff Zigbee TRVs (radiator valves) expose two `device_class: battery` entities, one a binary sensor that is meant to tell you when the battery is getting low and the other giving you its actual state in percent:
![Two battery entities for a single TRV device](https://github.com/maxwroc/battery-state-card/assets/609634/80032f23-0bd9-4fe3-9788-1f532a30a02e)

Using the default configuration, the card happens to pick up the first entity and shows an "Unknown" battery state for all TRVs:
![Battery states showing as "Unknown"](https://github.com/maxwroc/battery-state-card/assets/609634/058f7198-98f4-4660-a94f-1cbe3cc9e5dc)

This can be fixed by excluding any entities that are binary sensors, by adding the following to the `filter` section of the default card configuration:
```yaml
  exclude:
    - name: entity_id
      value: binary_sensor.*
```

With this, the battery states show correctly:
![Battery states showing correctly](https://github.com/maxwroc/battery-state-card/assets/609634/9ff75079-b4ea-48fd-bafc-4d041e70ca63)

It feels like filtering out binary sensors by default would be a sensible thing to do, given they cannot provide useful numerical values anyway (but there should still be an option to include them for people using the card to display some binary non-battery-state data).

**Comment by maxwroc** [comment]
I agree that the exclude filter for binary_entities in the default configuration make sense but it is weird that you don't see the other (sensor) entities on the list. Both entity types should be added just the binary ones should be listed at the top as the state is Unknown.

Can you please double check whether the "sensor" entities are not displayed somewhere at the bottom?

**Comment by plush** [comment]
You are right. I had missed it that if I expand the card, all TRVs show up a second time, with the correct battery status. So it is as you say - both sensors are picked up separately. And in the default sort order, the "unknown" ones are shown first.

**Comment by maxwroc** [comment]
Ok I will treat it not as a bug but enhancement ;)

**Comment by maxwroc** [comment]
In v3.1.4
