### ISSUE TITLE
Entity names always start with capital letter. Intended?

### ISSUE THREAD

**Issue by Stoffl17** [maxwroc/battery-state-card#647]
**Describe what is wrong**
Since a while all entity-names always start with a capital letter. This is not at all critical and might only be seen in special cases. For example if you have an "iPhone" the entity name starts with "**I**Phone".
Was this change intended and is there a chance to leave the entity name like it is set up by the user?

**Version**
v3.1.3

**Comment by maxwroc** [comment]
You can disable this via BulkRename capitalize_first
https://github.com/maxwroc/battery-state-card?tab=readme-ov-file#bulk-rename

Example (just skip the rules)
https://github.com/maxwroc/battery-state-card?tab=readme-ov-file#entity-filtering-and-bulk-renaming

**Comment by Stoffl17** [comment]
Thanks very much for the fast answer. It works.
Sorry that I oversaw that new config-setting, which has been introduced.

**Comment by maxwroc** [comment]
No worries, not your fault - it was kind of breaking change which shouldn't happen in the minor version update
