### ISSUE TITLE
Glance-Card Layout

### ISSUE THREAD

**Issue by embeddeddev** [maxwroc/battery-state-card#65]
Hey together,

it would be nice, if you could introduce another *layout option* that behaves like the builtin **Glance** card (https://www.home-assistant.io/lovelace/glance/) for a much more compact view when there are many entities present.

Looking forward for your estimation of feasibility.

**Comment by maxwroc** [comment]
This is what I was mentioning here: https://github.com/maxwroc/battery-state-card/issues/44#issuecomment-632098502

**Comment by maxwroc** [comment]
Please check custom styles and example in readme:
https://github.com/maxwroc/battery-state-card#extra-styles
