### ISSUE TITLE
Add the ability to show state when devices only present as a binary sensor

### ISSUE THREAD

**Issue by daknightuk** [maxwroc/battery-state-card#650]
When using Blink security cameras the battery state is presented as a binary sensor with state On (Battery low) or Off (Battery OK)

Whilst the state card works and shows the state, is it possible to show either a full battery or an empty battery rather than a battery with a ? in the centre of it

![image](https://github.com/maxwroc/battery-state-card/assets/84586585/b41f7bf9-41a0-4196-b725-7b5a40b07da9)

**Comment by maxwroc** [comment]
Look at the state_map there are examples in the documentation

**Comment by daknightuk** [comment]
All done and thank you :)

![image](https://github.com/maxwroc/battery-state-card/assets/84586585/dc72c58f-885f-4e3c-a535-2f687c7e2fa1)
