### ISSUE TITLE
Custom colour treshold only works with whole numbers (V.3.1.4)

### ISSUE THREAD

**Issue by digi303** [maxwroc/battery-state-card#653]
Custom colour treshold only works with whole numbers

Here is an example with temperatures:

Code:
[...]
sort: state
colors:
  steps:
    - value: 18
      color: lightblue
    - value: 19
      color: blue
    - value: 20
      color: yellow
    - value: 22
      color: green
    - value: 23
      color: red
    - value: 24
      color: darkviolet
tap_action:
  action: more-info
collapse: 10
entities:
  - entity: sensor.klimasensor_kuche_temperature
  - entity: sensor.klimasensor_gaste_wc_temperature
  - entity: sensor.hwr_h_t_sensor_temperature
  - [...]

Output with Decimal numbers:
![komma](https://github.com/maxwroc/battery-state-card/assets/94383598/fa07a749-3efb-4a95-a96c-2f6cbbb179a5)

Output with Integers:
![integer](https://github.com/maxwroc/battery-state-card/assets/94383598/b40700a7-a2ab-4f00-9135-875360444d3c)

**Comment by maxwroc** [comment]
Thanks for reporting - fixed in v3.1.5
