### ISSUE TITLE
Enable custom colors for all numeric values (also outside of 0-100 range)

### ISSUE THREAD

**Issue by maxwroc** [maxwroc/battery-state-card#656]
**Is your feature request related to a problem? Please describe.**

#599 has the details

**Describe the solution you'd like**

**Additional context**

**Comment by prfk** [comment]
Hi, any chance v3.3 is released soon?
I'd love to have the have custom colors for values >100.
Thank in advance

**Comment by milandzuris** [comment]
@maxwroc ???
