### ISSUE TITLE
Hide entity depending on Home Assistant's "Visible" setting

### ISSUE THREAD

**Issue by LazyTarget** [maxwroc/battery-state-card#658]
**Is your feature request related to a problem? Please describe.**

I would like to hide some unwanted entities. Instead of explicitly specifying them in the `battery-level-card`, it would be nice if I could use the native "Visible" property

**Describe the solution you'd like**

Home Assistant has a flag on every entity called "Visible". Would it be possible to listen to this setting and hide the entity if it was disabled?

**Additional context**

![image](https://github.com/maxwroc/battery-state-card/assets/959409/0d97f196-3d78-42a3-86a5-1d3127b96723)

**Comment by maxwroc** [comment]
Good idea! 

I will need to find out where I can get the info whether the entity is visible or not...

**Comment by maxwroc** [comment]
Added in v3.2.0
