### ISSUE TITLE
sort by stat doesn't work when the value is higher than 1000

### ISSUE THREAD

**Issue by vejvik** [maxwroc/battery-state-card#659]
I wanted to use the card to sort the consumption of individual appliances, but as soon as the consumption is higher than 1000W, when there is a gap between 1 and 0, the card does not sort this value

type: custom:battery-state-card
sort:
  desc: true
  by: state
collapse: 5
icon: mdi:lightning-bolt
unit: W
round: 0
entities:
  - entity: sensor.mycka_napajeni
    name: Myčka
  - entity: sensor.trouba_napajeni
    name: Trouba
  - entity: sensor.mikrovlnka_napajeni
    name: Mikrovlnka
  - entity: sensor.zasuvky_obyvak_power
    name: Zásuvky obývák
  - entity: sensor.lidl_zasuvka_kotel_active_power
    name: Kotel
  - entity: sensor.zasuvka_pc_active_power
    name: Počítač
  - entity: sensor.tasmota_zasuvka_energy_power
    name: Pračka
  - entity: sensor.zasuvka_lednice_mamina_active_power
    name: Lednice mamina
  - entity: sensor.zasuvka_lidl_active_power
    name: Lednice
  - entity: sensor.shelly1pm_349454757403_power
    name: bojler
title: co právě běží

# paste your card configuration here

```

**Screenshot**
`https://i.postimg.cc/T2kDbbtH/Sn-mek-obrazovky-2024-01-19-151224.png`

**Comment by maxwroc** [comment]
I see that the recent support for HA default formatting is causing a lot of trouble. 

You can mitigate the problem by adding the following to your config:
```yaml
default_state_formatting: false
```

The fix will be covered via this issue: #657
