### ISSUE TITLE
Adding Secondary Info

### ISSUE THREAD

**Issue by SergioFuchs** [maxwroc/battery-state-card#660]
How can I add a secondary info like this example:  sensor.{{device_name}}_battery_last_replaced ?

I'm trying to display the battery_last_replaced info that I got from:
https://github.com/andrew-codechimp/ha-battery-notes

Thanks

**Comment by maxwroc** [comment]
I'll be adding features related to recent battery-notes updates soon so it will be possible to achieve it.

Unfortunately now you cannot do it this way. You need to specify the entity name individually per battery

**Comment by SergioFuchs** [comment]
> I'll be adding features related to recent battery-notes updates soon so it will be possible to achieve it.
> 
> Unfortunately now you cannot do it this way. You need to specify the entity name individually per battery

Ok, I'll wait for next update

Thanks

**Comment by maxwroc** [comment]
Just to set the expectations right - I'm not sure if it will be in the "next" update ;) Please check release notes when minor version bumps (patches for sure won't have it)

**Comment by Johnymalina** [comment]
Hi i know its older topic but i would like to do the same and am not able to do. Is it implemented? I cant make it work using KStrings
