### ISSUE TITLE
Formatting issue secondary_info last_changed

### ISSUE THREAD

**Issue by erkr** [maxwroc/battery-state-card#663]
**Describe the bug**
Thanks for this really great card. I love it!!!
Ran into one of the small issues:
The stock example for secondary info works fine:
``` 
secondary_info: '{last_changed}'
``` 
Result:
![image](https://github.com/maxwroc/battery-state-card/assets/4363599/a3f8db5e-053a-423e-8ceb-c8fcfa783772)

But when I add some additional info, it fails:
``` 
secondary_info: 'since {last_changed}'
``` 
Result:
![image](https://github.com/maxwroc/battery-state-card/assets/4363599/fcfd0bee-51c0-48c9-b939-87212d07fe08)

**Version**

V3.1.5

**Comment by maxwroc** [comment]
This is expected. To convert value to relative time you need to pass it through the `reltime()` function
![image](https://github.com/maxwroc/battery-state-card/assets/8268674/5cd92ff4-f28d-4b05-a931-726a37ca00b2)

The only reason why `'{last_changed}'` works is that this was working like this before and when I have added the support for "having a relative-time values between the string" I didn't want to have a "breaking change" hence bumping major card version.

But I agree that now it can be confusing why the val alone works as expected but not between strings. 

Please reopen if it doesn't work with the above
