### ISSUE TITLE
Exclude battery level of phones and smartwatches

### ISSUE THREAD

**Issue by venator85** [maxwroc/battery-state-card#666]
Hi, how can I exclude phone and smartwatches battery levels from the list? I'd like to avoid to exclude them by their entity_id one by one, I'm wondering if it is possible to set a filter based on the device type of the battery sensor or something like that.
Do you have any hints?
Thanks

**Comment by maxwroc** [comment]
It is not possible now as currently entity doesn't have any info about the device but... this will be changing soon.

I cannot promise that this will solve your problem - it depends what kind of info exists in the device object which HA provides

Please check the next minor release

**Comment by RedNo7** [comment]
> Do you have any hints?

If you name their `entity_id` to always contain `mobile` (for example), you can exclude based on that:

```yaml
exclude:
  - name: entity_id
    value: "sensor.*mobile*"

**Comment by maxwroc** [comment]
FYI in v3.2.0 you have the option to use additional data for filtering.

You can check what all your phones and smart watches have there in common by adding a `debug: true` in the card configuration. This will show you all the data available per entity.

For example:
![image](https://github.com/maxwroc/battery-state-card/assets/8268674/5d262267-fde6-4358-befb-d06c3ffb0a08)

There is a platform set to mobile_app so by adding the following filter you should be able to exclude them:

```yaml
filter:
  exclude:
    - name: "device.platform"
      value: "mobile_app"
```

There might be the other way to do it - you just need to check what the entities which you want to exclude have in common and what is not present in all the others.

**Comment by RedNo7** [comment]
in `3.2.0` I have this working for `exclude`, but not `include`.  Is there a reason for that?

**Comment by maxwroc** [comment]
Yes, unfortunately "extended entity data" is not available for include filters. It is because it would require me to gather properties from various sources for all of the entities. Doing it on every state update can be problematic - waste of resources.

I thought I have mentioned this somewhere in the docs but now I don't see it. I'll need to add it as it can be indeed confusing.

In the future I will think about some other approach and will add it to "include" filter too

**Comment by RedNo7** [comment]
gotcha - thanks for clarifying!
