### ISSUE TITLE
Question mark on the icon

### ISSUE THREAD

**Issue by Rrapa** [maxwroc/battery-state-card#667]
**Describe the bug**
I seeing question mark on every icon 

**How to reproduce**

**Expected behavior**

**YAML configuration**
On simple card example

(type: custom:battery-state-card)

<img width="455" alt="Zrzut ekranu 2024-02-4 o 12 35 57" src="https://github.com/maxwroc/battery-state-card/assets/73557792/a04f8cf6-1d03-48ac-bcf4-d7d42399a1ea">

**Version**
3.1.5

**Comment by maxwroc** [comment]
Dupe #657
