### ISSUE TITLE
*FIXED* Colours not showing and sort order wrong

### ISSUE THREAD

**Issue by julian4646** [maxwroc/battery-state-card#675]
*EDIT* fixed by adding below (found in the forum):
default_state_formatting: false

**Describe the bug**
Not getting colours and sort order wrong 

**How to reproduce**
Happened after upgrade to 3.1.6

**Expected behavior**
Colors and sort order like before - lowest to highest

**Screenshots**
see attached

(https://github.com/maxwroc/battery-state-card/assets/36640799/f62f2ac2-12b4-4f29-ab84-13c5699c785e)

**Version**
3.1.6

**YAML configuration**
```yaml

# please paste here your card config

type: custom:battery-state-card
secondary_info: '{last_changed}'
filter:
  include:
    - name: attributes.device_class
      value: battery
  exclude:
    - name: entity_id
      value: sensor.third_reality_inc_3rms16bz_battery
sort:
  by: state
collapse: 4
bulk_rename:
  - from: ' Battery'
  - from: ' level'
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true

**Comment by maxwroc** [comment]
Are you sure you're on 3.1.6? Please check the browser console (F12 if you're on PC)

Look for something like the following:
![image](https://github.com/maxwroc/battery-state-card/assets/8268674/5ae745db-fc07-41d3-a327-cdcf62fd87c7)

**Comment by maxwroc** [comment]
Please re-open if you confirm that the problem exists on v3.1.6. 

Pretty often browser caches the old card code and you need to refresh page few times / clear browser cache.
