### ISSUE TITLE
Battery state card not change colors

### ISSUE THREAD

**Issue by ork777** [maxwroc/battery-state-card#676]
`type: custom:battery-state-card
title: Level Battery
color_thresholds:

    value: 35
    color: red
    value: 45
    color: blue
    value: 60
    color: orange
    value: 100
    color: green
    entities:
    entity: sensor.desktop_6gnjinv_battery_charge_remaining_percentage`

now it looks like this
![Screenshot 2024-02-10 at 17-42-44 Panoramica – Home Assistant](https://github.com/maxwroc/battery-state-card/assets/97830863/61f6930c-9677-497f-a4d4-0f37e98e6ab7)

`

**Comment by ork777** [comment]
working version of Home Assistant Core?

2024.1.6

**Comment by maxwroc** [comment]
Please always they the latest version of the card before creating the issue

**Comment by maxwroc** [comment]
I thought this was fixed but looks like it wasn't.... I guess you can be on the last card version already

Closing anyway as this is a dupe of #675
