### ISSUE TITLE
Could we have the option to show non-visible entities?

### ISSUE THREAD

**Issue by DChiuch** [maxwroc/battery-state-card#690]
I have all of my battery level entities set to non-visible so that they don't show on my other dashboards. But I love the battery-state-card because I can have a dashboard that shows these batteries together, regardless of their visibility status. Now that the card supports respecting Home Assistant's visibility setting, could we have a configuration option to still show non-visible entities?

**Comment by nechry** [comment]
Same for me, I discovered this morning that all my dashboards using the battery-state-card are empty because for me it is system information.

otherwise let me take this opportunity to congratulate you on this development full of possibilities and very well documented

**Comment by maxwroc** [comment]
Thx. Speaking about documentation... there is one undocumented switch (temporary one) which can help you to mitigate the problem :)

Set extend_entity_data to false. It will disable the new functionalities from the latest release.

**Comment by maxwroc** [comment]
Will be available in v3.3.0 - more details under linked PR
