### ISSUE TITLE
Entities not battery

### ISSUE THREAD

**Issue by mworsnop** [maxwroc/battery-state-card#695]
**Describe what is wrong**
its is seeing entities that are not battery related. These are from the ring door contact switches working on Z wave.  On the automation I can manually enter these for entities to stop them from being tested, but the display on the dashboard still has them anyway. And I have about a dozen of these door sensors that I would like to enable. Is that the best way for me to handle this? Just manually enter the four entities? See the attached screenshot.

**Version**
3.2.0
![Notification_Center](https://github.com/maxwroc/battery-state-card/assets/10225980/c5de125d-8cb8-4bf6-b7fd-075d457d2a2a)

**Comment by maxwroc** [comment]
Sorry but I don't fully understand the situation. I'll do my best to help but I would need more info to help I think.

First of all what is the card config you use? Is it the default one (just the card name/type)?

By default card shows all of the entities which have the device_class set to battery. You can have a look at the default config: https://github.com/maxwroc/battery-state-card?tab=readme-ov-file#default-card-config

![image](https://github.com/maxwroc/battery-state-card/assets/8268674/a802f504-b3df-4aae-a0f1-443edf9237b8)

It this is matching some of the unwanted entities you can filter them out via filter-exclude. It can be done by have individual rules for each entity_id you don't want or some other way if unwanted entities have same attributes/properties (to check properies of entities you can use `debug: true` setting in your card config).

If the Freezer, Door bell and Snop entities are not a battery ones it is quite weird that they have a `device_class: battery`. Are these the ones which are the unwanted? Seeing the output for these entities when the debug:true option is present would be very helpful

**Comment by mworsnop** [comment]
see the entries for "Garage Door Man" on the graphic.  They are Charging Status, Recharge..., Max Capacity, Temperate.  None of those are battery.  

The door bell could have a battery but its powered.  Freezer is a door contact to make sure its closed. It does have a battery.  It is showing up OK now. 

Sorry I am really new to HA, 5 days so far.  I can manually enter the unwanted entities. Thats not a problem I just thought you'd like to know about it

I used the default config.  I dont know where the config file is to add on the debug or try and add in the exclude into the config. 

Thank you so much for replying! Sorry Im a slow in understanding everything

**Comment by maxwroc** [comment]
No worries it looks like you have some weird integrations in your HA which are producing unexpected entities. I'd recommend seeking help on HA forum. It can be either a battery state card related thread or some other one. There will be more people who might be able to help.

I have no experience with any z-wave devices / integrations but having a 20 entries per device seems to be ridiculous
