### ISSUE TITLE
Exception: Cannot read properties of undefined (reading 'battery_level')

### ISSUE THREAD

**Issue by guber73** [maxwroc/battery-state-card#696]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**YAML configuration**
```yaml

# please paste here your card config (before backticks below; do not remove them)

```

***Entity debug data***

```json

```

**Dev console errors**

**Screenshots**

**Version**

**Comment by maxwroc** [comment]
There is only one place where this exception can happen and it would mean that you have an entity which doesn't have any attributes. I thought this cannot happen.

**Comment by pcampan** [comment]
Similar issue appeared in my instance about 12 hours ago.

**Comment by maxwroc** [comment]
Will be fixed in the next release

**Comment by maxwroc** [comment]
I have realized what was the actual reason of these errors. It was not the case of missing attributes of the entity but missing entity. In the next release when entity is not found you'll be seeing a proper message
