### ISSUE TITLE
Not sorting, colouring, etc. 

### ISSUE THREAD

**Issue by bushcraftytim** [maxwroc/battery-state-card#697]
Since an update to the latest version the batteries are not showing gradients or colours and not sorting. I have tried the card with no settings and copied and pasted the default config in and this doesn't change. It's only battery levels as the custom configs for wifi levels and movement sensors still work. The percentages are still shown and they are correct. 

Any ideas?

**Comment by maxwroc** [comment]
Without additional info I won't be able to help. Please provide screenshots, and entity data (add `debug: true` in the card config and copy-paste here the entity data - check [Troubleshooting](https://github.com/maxwroc/battery-state-card#troubleshooting) section in the docs)

**Comment by bushcraftytim** [comment]
Going to close this - uninstalling, restarting HA and re-installing fixed it.
