### ISSUE TITLE
Links in battery-state-card documentation just go to local HACS menu

### ISSUE THREAD

**Issue by pfurrie** [maxwroc/battery-state-card#705]
**Describe the bug**
Links in battery-state-card documentation just go to local HACS menu

**How to reproduce**
1. Open _HACS_
2. Open _Frontend_
3. Search for and open _Battery State Card / Entity Row_
4. Scroll down to _Card config_ section
5. Click on any link.  For example:
![image](https://github.com/maxwroc/battery-state-card/assets/11449721/7e99cce4-315f-4f59-908f-cb46bdfc6ca3)
6. Watch as you are whisked to the HACS main menu:
![image](https://github.com/maxwroc/battery-state-card/assets/11449721/48a3efa3-54a6-42a4-8830-3bf46e26e71a)

**Expected behavior**
The user would be shown a page with information regarding the link that was clicked.  As in the above example, something about _entities_.

**YAML configuration**
```yaml

# please paste here your card config (before backticks below; do not remove them)

```

***Entity debug data***

This isn't within the card itself.

**Dev console errors**

Not an error in the card.

**Screenshots**
This shows one of the addresses pointed to by a link.  Each link does have a different address that looks like it should work, but doesn't do what you think it might do.
![image](https://github.com/maxwroc/battery-state-card/assets/11449721/7d1f6b80-0223-4167-adaa-ca4d50a54b50)

**Version**
3.2.1

![image](https://github.com/maxwroc/battery-state-card/assets/11449721/81ed5df1-4ede-4b32-bbac-70ae0eb52de7)

**Comment by maxwroc** [comment]
This issue should be reported on the HACS side. The links in the doc are relative, not absolute:
![image](https://github.com/maxwroc/battery-state-card/assets/8268674/43c489d5-a911-403c-b77c-16ec95de319b)

![image](https://github.com/maxwroc/battery-state-card/assets/8268674/6f7c7be9-06e9-4f6f-8f2a-dde36661e906)

I bet the same problem applies to other plugins/components.
