### ISSUE TITLE
How can I show battery level and pass info is charging in same device with two different entities

### ISSUE THREAD

**Issue by polpas** [maxwroc/battery-state-card#712]
I have a device roomba.

I can get battery level through entity sensor.irobot_bateria. But I need to pass a secondary info when the device is docked that is charging. How can I do it?

**Comment by polpas** [comment]
I can get entity vacuum.irobot whith value docked - it means that is charging
I can get sensor.robot.bateria that show battery level.

What I wanted to do is if sensor.robot_bateria is is less than 100% and vacuum.irobot is docked I wanted to pass the text is charging with the battery level displayed as in normal template

**Comment by polpas** [comment]
Yes I followed your templates but I cant get it right.

sensor.idalina_bateria is returning the level of bateria
vacuum.idalina is returning the value docked

<img width="1149" alt="vacuum-idalina" src="https://github.com/maxwroc/battery-state-card/assets/14005842/836dcff4-04a6-4587-ada0-9b1f6dc8ac1d">

<img width="1124" alt="sensor idalina" src="https://github.com/maxwroc/battery-state-card/assets/14005842/b6961af7-5c3a-45a8-ab88-e582c965c35b">

I wanted to pass secondary text if value is docked.
<img width="1115" alt="Captura de ecrã 2024-03-11, às 12 38 28" src="https://github.com/maxwroc/battery-state-card/assets/14005842/265e9e75-e46a-4026-90ea-96cef2b1c185">

**Comment by maxwroc** [comment]
This is almost right:
![image](https://github.com/maxwroc/battery-state-card/assets/8268674/1f746ecc-e6ab-44c1-85cf-8fc1a1747a52)

Although you're telling the card that the "charging state" can be found in the attribute "is_charging" of the same entity.

If you take a look at the "charging_state" object/config you can specify entity ID where the charging state should be searched for. 

So sth like the following:
```yaml
charging_state: # uses other entity state value
  entity_id: vacuum.xxxx
  state: "docked"
```

**Comment by polpas** [comment]
Ok I'm getting there however In two different devices I have two different behaviors:

in iPhone Francisco I have the text charging but in iRobot device even the symbol charging appear the text does not how come?

<img width="987" alt="Captura de ecrã 2024-03-11, às 13 47 55" src="https://github.com/maxwroc/battery-state-card/assets/14005842/ef3bcdfe-268f-4c4f-a014-173c87c61fe2">

**Comment by polpas** [comment]
secondary info was passing docked instead of charging


- entity: sensor.idalina_bateria
    name: iRobot Idalina
    secondary_info: "{charging}" # only appears 
#   when is docked 
    charging_state:
      entity_id: vacuum.idalina
      state: "docked"
      secondary_info_text: "Charging in progress"
#   override for "Charging" text
