### ISSUE TITLE
Allow batteries set to not visible to be shown if directly added under entities.

### ISSUE THREAD

**Issue by KINGCanty** [maxwroc/battery-state-card#718]
Batteries set to not visible don't show in the card, even when added under entities.

I would like for them to show if directly added under entities, it would also be nice to have a include filter to show all?

**Comment by folfy** [comment]
> This will be possible to achieve in the next version via dedicated setting: #698

Hate being "that guy*, but can we get a new version tagged? ;D
Like, I'd help, if you need something tested or fixed, but I guess there's not much more we can support in this.
