### ISSUE TITLE
Exception: undefined is not an object (evaluating 'n.attributes')

### ISSUE THREAD

**Issue by Gaeta92** [maxwroc/battery-state-card#734]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**YAML configuration**
```yaml

# please paste here your card config (before backticks below; do not remove them)

```

***Entity debug data***

```json

```

**Dev console errors**

**Screenshots**

**Version**

**Comment by maxwroc** [comment]
Closing due to missing any details
