### ISSUE TITLE
filter by range value

### ISSUE THREAD

**Issue by peceq** [maxwroc/battery-state-card#742]
How can i show entities only with battery level lower than for example 30% ? 
How can i show entites except state :  unavailable or unknown
Thanks for your answer
Best Regards.

**Screenshot**
![image](https://github.com/user-attachments/assets/01c0a61f-298b-4114-848b-254b590364bd)

**Version**
V3.2.1

**Comment by WilbertWilbers** [comment]
exclude:
    - name: state
      value: 30
      operator: >

**Comment by peceq** [comment]
> exclude: - name: state value: 30 operator: ">"

Thanks, it works

**Comment by peceq** [comment]
Sugestion checked and works well
