### ISSUE TITLE
Any additional option breaks the card

### ISSUE THREAD

**Issue by ecdeveloper** [maxwroc/battery-state-card#748]
**Describe what is wrong**
The moment I add _any_ option to the card except for `type` - no content is shown as if the card config was broken.

**YAML configuration**
```yaml

type: custom:battery-state-card
title: "Batteries"

```

**Screenshot**
<img width="1025" alt="Screenshot 2024-11-11 at 7 09 13 PM" src="https://github.com/user-attachments/assets/a9ecb5d8-400c-4586-825d-09a1eaed0e90">
<img width="1021" alt="Screenshot 2024-11-11 at 7 09 26 PM" src="https://github.com/user-attachments/assets/7971eabb-9597-4952-ba35-34f8021adaaf">

**Version**
`v3.2.1`

Thank you in advance!

**Comment by chrisannen** [comment]
Exactly same Problem here 🖐️ HA-Version 2024.10.4.

**Comment by chrisannen** [comment]
OK, i found the solution. When you modify the code, you have to set the "include-filter" like this:

filter:
  include:
    - name: attributes.state
      operator: exists
    - name: attributes.device_class
      value: battery

![image](https://github.com/user-attachments/assets/4769a55c-f23b-4a0c-ad5a-847328953b18)
